#!/bin/bash
set -e 

docker stop $(docker ps -q) || true
docker rm $(docker ps -aq) || true

docker pull cloudsuite/web-serving:db_server
echo 'run db server'
docker run -dt --net=host --name=mysql_server cloudsuite/web-serving:db_server 10.254.0.98

docker pull cloudsuite/web-serving:memcached_server
docker run -dt --net=host --name=memcache_server cloudsuite/web-serving:memcached_server

docker pull cloudsuite/web-serving:web_server
docker run -e "HHVM=true" -dt --net=host --name=web_server_local cloudsuite/web-serving:web_server /etc/bootstrap.sh 10.254.0.98 10.254.0.98 

echo 'run benchmark'
docker pull cloudsuite/web-serving:faban_client
#run
sudo perf stat -e cache-misses,page-faults -a docker run --net=host --name=faban_client cloudsuite/web-serving:faban_client 10.254.0.98 10 || true

docker stop $(docker ps -q) || true
docker rm $(docker ps -aq) || true
