#!/bin/bash

set -e 

docker stop $(docker ps -q) || true
docker rm $(docker ps -aq) || true

if [ $(($1%3)) -eq 0 ]
then
    CNT=4
elif [ $(($1%3)) -eq 1 ]
then
    CNT=1
else
    CNT=2
fi

docker build -t cloudsuite/data-caching:client benchmarks/data-caching/client --no-cache
#docker build -t cloudsuite/data-caching:server benchmarks/data-caching/server
docker build -t cloudsuite/memcached commons/memcached/1.5.20

docker network create caching_network || true

docker pull cloudsuite/data-caching:server

count=0
while [ $count -lt $CNT ]
do
    docker run --name dc-server$count --net caching_network -d cloudsuite/data-caching:server -t 4 -m 4096 -n 550
    ((count=count+1))
done


#run
echo 'execute benchmark'
sudo perf stat -e cache-misses,page-faults -a docker run -it --name dc-client --net caching_network cloudsuite/data-caching:client /tmp/run_caching.sh $1 || true

docker stop $(docker ps -q) || true
docker rm $(docker ps -aq) || true
